engines:

  duplication:
    enabled: true
    config:
      languages:
        php:
          mass_threshold: 200

  fixme:
    enabled: true

  phpmd:
    enabled: true
    checks:
      CleanCode/StaticAccess:
        enabled: false

ratings:
  paths:
  - "**.php"
