engines:

  duplication:
    enabled: true
    config:
      languages:
        php:
          mass_threshold: 40
    exclude_fingerprints:

  fixme:
    enabled: true

  phpmd:
    enabled: true
    checks:
      CleanCode/StaticAccess:
        enabled: false
    exclude_fingerprints:
      - 5a5f94d601abbfbcfc9414d05bdfc022
      - 672c6ef99238e62865f6211a3cd031c0

ratings:
  paths:
  - "**.php"