language: php

dist: trusty

matrix:
  include:
    - php: '5.6'
      env: WITH_CS=true
    - php: '7.0'
    - php: '7.1'
    - php: '7.2'
    - php: '7.3'
    - php: hhvm
    - php: nightly

cache:
  directories:
    - $HOME/.composer/cache

before_script:
  - composer validate
  - composer install

script:
  - if [[ "$WITH_CS" == "true" ]]; then composer require --dev friendsofphp/php-cs-fixer:^2.1.0 && bin/php-cs-fixer fix --config=.php_cs --diff --dry-run --verbose; fi
  - bin/phpunit

after_success:
  - composer require codeclimate/php-test-reporter dev-master
  - bin/test-reporter

notifications:
  email:
    on_success: change
    on_failure: change

addons:
  code_climate:
    repo_token: 5b8d35683519492fa56ed775ae82e48a6f59e44ab64aaf2e5d254b23fbb842ca
