language: php

php:
  - '5.6'
  - '7.0'
  - '7.1'
  - hhvm
  - nightly

cache:
  directories:
    - $HOME/.composer/cache

before_script: composer install --no-dev

script:
  - bin/phpunit

after_success:
  - composer require codeclimate/php-test-reporter dev-master
  - bin/test-reporter

notifications:
  email:
    on_success: change
    on_failure: change

addons:
  code_climate:
    repo_token: 5b8d35683519492fa56ed775ae82e48a6f59e44ab64aaf2e5d254b23fbb842ca
