language: php

php:
  - '5.6'
  - '7.0'
  - '7.1'
  - hhvm
  - nightly

cache:
  directories:
    - vendor
    - bin

before_script: composer install --no-dev

notifications:
  email:
    on_success: change
    on_failure: change
